### ISSUE TITLE
Cut/Paste affecting UIBarButtonItem

### ISSUE THREAD

**Issue by mofolo** [hanspinckaers/GrowingTextView#14] opened 2012-04-11 23:04 UTC
There seems to be a problem when you cut all text from the GrowingTextView or paste large amounts of text into an empty GrowingTextView. The images can explain it a little better:

**When Pasting into empty TextView**
![Pasting Image](http://i.stack.imgur.com/ZLM94.png)
As you can see, the UIBarButtonItem gets affected in a weird way. 

**When Cutting or Clearing the field to empty**
![Cutting](http://i.stack.imgur.com/XzsQ2.png)
Same deal here, the UIBarButtonItem gets pushed below the Toolbar's view.

**When you enter text normally, paste into a non empty textView, or if not all characters are cut/cleared
![How it should be](http://i.stack.imgur.com/ytXkP.png)

**Comment by hanspinckaers** [comment] 2012-04-13 10:49
Thanks, this means that the delegate method for height changed doesn't get called when using cut/copy/paste. 

I don't have much time, maybe you can find a solution? Just listen to cut/copy/paste actions and call the delegate. 

Hans

**Comment by mofolo** [comment] 2012-04-15 13:46
I though the same too, but really, the delegate is returning the correct height when copying and pasting.

I ended up making my own UIButton and Putting it into the Toolbar, that solved the problem for me, but it still doesn't work with UIBarButtons.

**Comment by hanspinckaers** [comment] 2012-04-23 12:33
It's weird, but not a bug of GrowingTextView, so I'm closing this issue. Thanks for your report.

**Closed as completed by hanspinckaers** 2012-04-23 12:33 UTC
